### ISSUE TITLE
Meta robots

### ISSUE THREAD

**Issue by tablatronix** [GetSimpleCMS/GetSimpleCMS#596]
Add meta robots

* no index
* no follow
* no archive

Add as checkboxes for adding additional future toggles.

Already added as a combobox, redo as checkboxes.

- [x] Add no archive
- [x] Redo as checkboxes

**Comment by cnb** [comment]
Should pages with *noindex* enabled be excluded from the Sitemap?

**Comment by tablatronix** [comment]
Probably
- [ ] exclude no-index from sitemap

**Comment by tablatronix** [comment]
for reference
`metarNoIndex`,
`metarNoFollow`,
`metarNoArchive`,
