### ISSUE TITLE
gsconfig definitions

### ISSUE THREAD

**Issue by tablatronix** [GetSimpleCMS/GetSimpleCMS#982]
All global variables that are not actual variables and code wide enviromentals, have been converted to constants.

This might be refactored further into extendable configs, as of right now I am still using constants as we always have been. We will probably want this to be 4 distinct groups.
- GS CORE constants - _core wide constants_ - defined in common or environment
  -  GS USER definitions - user configurable - defined in `gsconfig.php` or environment, will be initialized to defaults at runtime
  - GS runtime configs - variables that we allow to change after runtime or by plugins in real-time or at some post `common` init time
  - GLOBALS - for now we are stuck with some of these, but they need to be documented and standardized, eventually they should go away

Currently there is the following
- `$GS_constants` constants that are not user definable in gsconfig or settable after runtime
- `$GS_definitions` constants that are user definable in gsconfig but will be set to defaults when not
- `Runtime` There is no feature for this yet
- `GLOBALS` like $id, $data_index, $EDHEIGHT, $EDTOOL, $LANG , some of these need to be chosen to be allowed in gsconfig, as they are now initialized properly, as of now most globals cannot be set in gsconfig anymore

These are all initialized dynamically using wrappers so we can modify this at anytime to set and unset configuration objects of any kind, this with getdef allows us to change out the config runtimes.
We can add a loader for yaml or json objects instead of gsconfigs `constants` or memcache

You can see these here
https://github.com/GetSimpleCMS/GetSimpleCMS/blob/master/admin/inc/common.php
### Todo
- [ ] decide which if any globals we allow set in gsconfig, I say none
- [ ] decide what we might want to move from CORE to USER
- [ ] decide on defaults when not set by gsconfig
- [ ] decide which ones need to be added to gsconfig, its possible that we do not want to add every  -  single possible minor or advanced case one to it, of course they will all be documented in wiki.

**Comment by cnb** [comment]
If a plugin needs to change any of these, should it access globals `$GS_definitions` and `$GS_constants` or do you plan to have some function for this?

Do you have a list of gsconfig settings for 3.4+ ? (If not, I can parse it and compare with 3.3.13)

**Comment by tablatronix** [comment]
Plugins cannot change definitions(constants), so that is something I need to figure out, I also do not want undefined constants, it is bad practice. So we need to decide what we will allow to be runtime modified and move them to some other method using a global config array for things that we allow users to change at runtime.

**Comment by cnb** [comment]
I thought you were moving these to arrays precissely so that they could be modified in runtime (by plugins or whatever)

**Comment by tablatronix** [comment]
Not yet

**Comment by tablatronix** [comment]
updated

**Comment by webketje** [comment]
@tablatronix in the https://github.com/GetSimpleCMS/GetSimpleCMS/issues/982#issuecomment-66556221, GSSAFEMODE is in there twice. Also, won't safe mode *ironically* break the non-admin part if plugin functions are used in the templates? 
I take interest in this issue because of the plugin GSConfig UI.

**Comment by tablatronix** [comment]
yeah it will pretty much break everything but allow you into admin if something is fatal
